# Generated by Django 5.0.3 on 2024-06-10 04:00

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_dealoftheday_days_alter_dealoftheday_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
