# Generated by Django 5.0.3 on 2024-06-11 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dealoftheday',
            options={},
        ),
        migrations.RemoveField(
            model_name='dealoftheday',
            name='created',
        ),
        migrations.RemoveField(
            model_name='dealoftheday',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='dealoftheday',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='dealoftheday',
            name='updated',
        ),
    ]
