# Generated by Django 5.0.3 on 2024-06-11 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_dealoftheday_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealoftheday',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
