# Generated by Django 5.0.3 on 2024-06-22 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_dealoftheday_is_offer_end'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dealoftheday',
            options={'ordering': ('id',), 'verbose_name': 'Deal Of The Day', 'verbose_name_plural': 'Deal Of The Days'},
        ),
        migrations.AddField(
            model_name='productimage',
            name='color',
            field=models.CharField(blank=True, default='#fff', help_text='Color of the product image', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(help_text='The recommended size is 800x600 pixels.', upload_to='products/'),
        ),
    ]
