# Generated by Django 5.0.3 on 2024-06-11 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoryoffer',
            name='is_new_arrival',
        ),
        migrations.RemoveField(
            model_name='categoryoffer',
            name='is_popular',
        ),
        migrations.RemoveField(
            model_name='categoryoffer',
            name='is_top_selling',
        ),
    ]
