# Generated by Django 5.0.3 on 2024-06-11 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_categoryoffer_sub_title_categoryoffer_title_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryoffer',
            options={'verbose_name': 'Offer By Category', 'verbose_name_plural': 'Offer By Categories'},
        ),
        migrations.RemoveField(
            model_name='categoryoffer',
            name='sub_title',
        ),
    ]
