# Generated by Django 5.0.3 on 2024-07-04 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_banner_subtitle_banner_tag_banner_title_offerbanner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='subtitle',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='banner',
            name='tag',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='banner',
            name='title',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
