# Generated by Django 5.0.3 on 2024-07-04 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_product_brand'),
        ('web', '0006_alter_banner_subtitle_alter_banner_tag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerbanner',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.subcategory'),
            preserve_default=False,
        ),
    ]
